### PR TITLE
fixes #76

### LINKED ISSUE #76: lrp failing with gninavis
### Issue summary

lrp in gninavis failure issues. I suspect that it has to do with adding some Hydrogen atoms that are not present in the original file, and failing to remove them before writing out.

### Steps to reproduce

Example can be found in  [fail_ex.tar.gz](https://github.com/gnina/gnina/files/3473551/fail_ex.tar.gz). Simply untar it, then cd into the directory and run the following command:

gninavis --receptor 1zog_nowat_4.pdb --ligand 1zog_docked_4.sdf --cnn_model gnina_test_ref.model --cnn_weights it2_completeset_DEF2018_s0.0_iter_1732000.caffemodel --atoms_only --vis_method lrp --gpu 0

### Your system configuration
(this was run on our cluster)

### PR DESCRIPTION
**Pull request by Jsunseri**

### CODE REVIEW

File: gninasrc/gninavis/cnn_visualization.cpp [hunk 1]
```diff
@@ -520,9 +520,9 @@ std::string cnn_visualization::get_xyz(const std::string &line) {
   std::string z = line.substr(46, 8);
 
   //avoid negative zeros in string representation
-  if (x == "-0.000") x = "0.000";
```
Comment (dkoes) [inline gninasrc/gninavis/cnn_visualization.cpp]: the trim_left below will remove the inserted space anyway. This is disturbingly nonrobust.

Comment (Jsunseri) [reply gninasrc/gninavis/cnn_visualization.cpp]: i agree, i considered making it more robust but figured since you let the original version slide i'd be lazy
